name: falaalgumacoisa
description: Voice recording (PT-BR) in Flutter
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  path_provider:
  http: '0.12.1'
  flutter_audio_recorder: '0.5.5' #https://pub.dev/packages/flutter_audio_recorder
  audioplayer: 0.8.1
  audioplayer_web: 0.7.1
  firebase_core: ^0.4.5
  # Auth
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  firebase_analytics: ^5.0.14
  firebase_remote_config: ^0.3.1
  get_it: '4.0.2'
  cupertino_icons: ^0.1.3
  shared_preferences: '>=0.5.7+3 <2.0.0'
  flutter_bloc: '4.0.0'
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/config.json
    - assets/google_logo.png