version: 2.1
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: mkdir -p assets && echo '{}' > assets/config.json
      - run: flutter doctor
      - run: flutter test 
      - run: flutter -v build apk